### ISSUE TITLE
IOError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by rzr** [pimoroni/rgbmatrix5x5-python#17]
Hi,

I am testing this i2c module:
https://shop.pimoroni.com/products/5x5-rgb-matrix-breakout#show-reviews

on "Raspbian GNU/Linux 10 (buster)"  and observing this issue:

```
curl https://get.pimoroni.com/rgbmatrix5x5 | bash

pi@raspberrypi:~/Pimoroni/rgbmatrix5x5/examples $ ./blinkyspot.py 
Traceback (most recent call last):
  File "./blinkyspot.py", line 53, in <module>
    rgbmatrix5x5.show()
  File "/usr/local/lib/python2.7/dist-packages/rgbmatrix5x5/is31fl3731.py", line 283, in show
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/rgbmatrix5x5/is31fl3731.py", line 105, in setup
    raise e
IOError: [Errno 121] Remote I/O error

i2cdetect -l
# i2c-1   i2c             bcm2835 (i2c@7e804000)                  I2C adapter

i2cdetect -y 1
# 70: -- -- -- -- 74 -- -- --      

cat /proc/device-tree/model 
# Raspberry Pi 4 Model B Rev 1.4
```

Can you please help to troubleshot this ?

**Comment by Gadgetoid** [comment]
Could be a wiring/connection issue. How’s it wired up?

**Comment by rzr** [comment]
yes ground was flaky thx
